name: Rust

on:
  push:
    branches:
      # two reserved branches for bors the bot
      - staging
      - trying
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --all-targets --workspace
      - run: cargo test --all-targets --workspace

  redox_check:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup default nightly
          rustup target add x86_64-unknown-redox
      - run: cargo check --all-targets --workspace --target x86_64-unknown-redox

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  minimum-rust-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup toolchain install 1.34.0
          rustup default 1.34.0
          rustup target add \
            x86_64-pc-windows-gnu \
            x86_64-apple-darwin \
            x86_64-pc-windows-msvc
      - run: |
          for target in x86_64-pc-windows-gnu x86_64-apple-darwin x86_64-pc-windows-msvc; do
            echo "== checking $target =="
            cargo check --all-targets --all --target "$target"
          done
        shell: bash

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup component add clippy
          rustup target add \
            x86_64-pc-windows-gnu \
            x86_64-apple-darwin \
            x86_64-pc-windows-msvc
      - run: |
          for target in x86_64-pc-windows-gnu x86_64-apple-darwin x86_64-pc-windows-msvc; do
            echo "== checking $target =="
            cargo check --all-targets --all --target "$target"
            git ls-files '*lib.rs' | xargs touch
            # FIXME: Remove `-- -A clippy::option_as_ref_deref` when MSRV is bumped past 1.40.0
            cargo clippy --all-targets --all --target "$target" \
              -- \
              -A clippy::option_as_ref_deref \
              -A clippy::redundant_field_names
          done
        shell: bash

  # These jobs doesn't actually test anything, but they're only used to tell
  # bors the build completed, as there is no practical way to detect when a
  # workflow is successful listening to webhooks only.
  #
  # ALL THE PREVIOUS JOBS NEED TO BE ADDED TO THE `needs` SECTION OF THIS JOB!
  end-success:
    name: bors build finished
    runs-on: ubuntu-latest
    needs: [build, redox_check, rustfmt, minimum-rust-version]
    # if: github.event.pusher.name == 'bors' && success()
    if: success()
    steps:
      - run: |
          echo "${{ github.actor }}"
          echo "${{ github.base_ref }}"
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"
          echo "${{ github.event.pusher.name }}"
      - name: mark the job as a success
        run: exit 0
  end-failure:
    name: bors build finished
    runs-on: ubuntu-latest
    needs: [build, redox_check, rustfmt, minimum-rust-version]
    # if: github.event.pusher.name == 'bors' && (failure() || cancelled())
    if: (failure() || cancelled())
    steps:
      - name: mark the job as a failure
        run: exit 1
